// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-3d/CampusGlobe.tsx": () => import("../components/mockups/hero-3d/CampusGlobe.tsx"),
  "./components/mockups/hero-3d/RadarPulse.tsx": () => import("../components/mockups/hero-3d/RadarPulse.tsx"),
  "./components/mockups/hero-3d/ShieldCosmos.tsx": () => import("../components/mockups/hero-3d/ShieldCosmos.tsx")
};
